name: dealermaster
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  carousel_slider: ^4.0.0
  cross_connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  dio: ^4.0.4
  file_picker: ^4.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.1
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.0
  flutter_typeahead: ^3.2.4
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  formz: ^0.4.1
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  nepali_date_picker: ^5.2.0
  nepali_utils: ^3.0.2
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  sentry: ^6.2.2
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  simple_gradient_text: ^1.2.2
  url_launcher: ^6.0.17

dev_dependencies:
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lang/
    - .env

  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Ubuntu-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
